csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'csvs'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
]

dj_pd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('performance/', include('products.urls', namespace='products')),
    path('upload/', include('csvs.urls', namespace='csvs'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import add_purchase_view, chart_select_view

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-product-view'),
    path('add/', add_purchase_view, name='add-purchase-view')
]

csvs/models.py
from django.db import models

# Create your models here.

class Csv(models.Model):
    file_name = models.FileField(upload_to='csvs/', max_length=100)
    uploaded = models.DateTimeField(auto_now_add=True)
    activated = models.BooleanField(default=False)

    def __str__(self):
        return "File id: {}".format(self.id)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=220)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField(blank=True)
    salesman = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        self.total_price = self.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return "Solled {} - {} items for {} , date - {}".format(self.product.name, self.quantity, self.total_price, self.date)

csvs/forms.py
from django import forms
from .models import Csv

class CsvForm(forms.ModelForm):
    class Meta:
        model = Csv
        fields = ('file_name',)

products/forms.py
from django import forms
from .models import Purchase, Product

class PurchaseForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(),
                                    label='Product',
                                    widget=forms.Select(attrs={'class': 'ui selection dropdown field-with'}))
    class Meta:
        model = Purchase
        fields = ['product', 'price', 'quantity']

csvs/views.py
from django.shortcuts import render
from .forms import CsvForm
from .models import Csv
import csv
from django.contrib.auth.models import User
from products.models import Product, Purchase

# Create your views here.

def upload_file_view(request):
    error_message = None
    success_message = None
    form = CsvForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = CsvForm()
        try:
            obj = Csv.objects.get(activated=False)
            with open(obj.file_name.path, 'r') as f:
                reader = csv.reader(f)

                for row in reader:
                    # opton to make data into list
                    # row = "".join(row)
                    # row = row.replace(";", " ")
                    # row = row.split()
                    print(row, "---", type(row))
                    user = User.objects.get(id=row[3])
                    prod, _ = Product.objects.get_or_create(name=row[0])
                    Purchase.objects.create(
                        product=prod,
                        price = int(row[2]),
                        quantity = int(row[1]),
                        salesman = user,
                        date = row[4] + " " + row[5]
                    )
                    print("added 1 row")

            obj.activated=True
            obj.save()
            success_message = "Uploaded successfully"
        except:
            error_message = "Ups. Something went wrong...."

    context = {
        'form': form,
        'success_message': success_message,
        'error_message': error_message,
    }
    return render(request, 'csvs/upload.html', context)

products/views.py
from django.shortcuts import render
from .models import Product, Purchase
import pandas as pd
from .utils import get_simple_plot
from .forms import PurchaseForm

# Create your views here.

def chart_select_view(request):
    graph = None
    error_message = None
    df = None
    price = None

    try:
        # qs1 = Product.objects.all().values()
        product_df = pd.DataFrame(Product.objects.all().values())
        purchase_df = pd.DataFrame(Purchase.objects.all().values())
        product_df['product_id'] = product_df['id']
    

    
        if purchase_df.shape[0] > 0:
            df = pd.merge(product_df, purchase_df, on='product_id').drop(['id_y', 'date_y'], axis=1).rename({'id_x': 'id', 'date_x': 'date'}, axis=1)
            price = df['price']
            if request.method == 'POST':
                chart_type = request.POST['sales']
                date_from = request.POST['date_from']
                date_to = request.POST['date_to']

                df['date'] = df['date'].apply(lambda x: x.strftime('%Y-%m-%d'))
                df2 = df.groupby('date',as_index=False)['total_price'].aggregate('sum')

                if chart_type != "":
                    if date_from != "" and date_from != "":
                        df = df[(df['date'] > date_from) & (df['date'] < date_to)]
                        df2 = df.groupby('date',as_index=False)['total_price'].aggregate('sum')
                    # function to get a graph   
                    graph = get_simple_plot(chart_type, x=df2['date'], y=df2['total_price'], data=df) 
                else:
                    error_message = 'Please select a chart type to continue'
        else:
            error_message = 'No record in the database'

    except:
        product_df = None
        purchase_df = None
        error_message = 'No record in the database'
    
    context = {
        'graph': graph,
        'price': price,
        'error_message': error_message,
    }
    return render(request, 'products/main.html', context)

def add_purchase_view(request):
    added_message=None
    form = PurchaseForm(request.POST or None)

    if form.is_valid():
        obj = form.save(commit=False)
        obj.salesman = request.user
        obj.save()

        form = PurchaseForm()
        added_message = "The purchase has been added"

    context = {
        'form': form,
        'added_message': added_message,
        }
    return render(request, 'products/add.html', context)

csvs/templates/csvs/upload.html
{% extends 'base.html' %}

{% block title %}upload{% endblock title %}

{% block content %}

    {% if success_message %}
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">
            {{success_message}}
        </div>
    </div>
    {% endif %}
    {% if error_message %}
    <div class="ui nagative message">
        <i class="close icon"></i>
        <div class="header">
            {{error_message}}
        </div>
    </div>
    {% endif %}
    <h1>upload</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="ui form">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="ui positive button">Add data</button>
    </form>

{% endblock content %}

products/templates/products/add.html
{% extends 'base.html' %}

{% block title %}add purchase{% endblock title %}

{% block content %}

{% if added_message %}
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">
            {{ added_message }}
        </div>
    </div>
{% endif %}


<form action="" method="POST" class="ui form">
    {% csrf_token %}
    {{form}}
    <button type='submit' class='ui positive button mtop'>Add sales data</button>
</form>
{% endblock content %}

products/templates/products/main.html
{% extends 'base.html' %}

{% block title %}performace{% endblock title %}

{% block content %}

<div class="ui modal mymodal">
   <div class="header"><h1>Price data</h1></div>
   <div class="ui container">
      <ul>
         <li><strong>Count: </strong> {{price.count}}</li>
         <li><strong>Mean: </strong> {{price.mean}}</li>
         <li><strong>Median: </strong> {{price.median}}</li>
         <li><strong>Min: </strong> {{price.min}}</li>
         <li><strong>Max: </strong> {{price.max}}</li>
         <li><strong>Std dev: </strong> {{price.std | floatformat}}</li>
      </ul>
   </div>
</div>

<div>
   <div class="block-center">
      {% if error_message %}
      <div class="ui negative message">
         <i class="close icon"></i>
         <div class="header">
            {{ error_message }}
         </div>
      </div>
      {% endif %}

      {% if request.POST %}
      {% if graph %}
      <img src="data:image/png;base64, {{ graph | safe}}">
      {% endif %}
      {% endif %}
   </div>
   <form action="" method="POST" class="ui form">
      {% csrf_token %}
      <div class="field">
         <label>Choose a chart type:</label>
         <div class="ui selection dropdown">
            <input type="hidden" name="sales">
            <i class="dropdown icon"></i>
            <div class="default text">----</div>
            <div class="menu">
               <div class="item" value="bar">Bar plot</div>
               <div class="item" value="line">Line plot</div>
               <div class="item" value="count">Count plot</div>
            </div>
         </div>
      </div>
      <div class="field">
         <div class="two fields">
            <div class="field">
               <label>Date from: </label>
               <input type="date" name="date_from">
            </div>
            <div class="field">
               <label>Date to: </label>
               <input type="date" name="date_to">
            </div>
         </div>
      </div>
      <div class="block-center">
         <button class="ui primary button" type='submit'>Select</button>
      </div>
   </form>
   <div class="block-center">
      <button class="ui secondary button" id='modal-btn'>See summary</button>
      <br>
      <a href="{% url 'products:add-purchase-view' %}"><button class='ui positive button'>Add record</button></a>
   </div>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- Custom css -->
    <link rel="stylesheet" type='text/css' href={% static 'style.css' %}>

    <!-- Semantic UI -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>DJ PD Proj | {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="ui container">
        {% block content %}
        {% endblock content %}
    </div>


    <!-- Custom js -->
    <script type='text/javascript' src={% static 'main.js' %}></script>
</body>

</html>

templates/navbar.html
{% url 'products:main-product-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}

<div class="ui secondary pointing menu">
    <a class="item">
        Home
    </a>
    <a href="{{path_to_performance}}" class="{% if request.path == path_to_performance %}active{%endif%} item">
        Performance
    </a>
    <a href="{{path_to_adding_records}}" class="{% if request.path == path_to_adding_records %}active{%endif%} item">
        Add records
    </a>
    <a href="{{path_to_upload}}" class="{% if request.path == path_to_upload %}active{%endif%} item">
        Upload file
    </a>
    <div class="right menu">
        <a class="ui item">
            Logout
        </a>
    </div>
</div>